--- 
title: "CO2 Emission Data Analysis"
author: "Hanlin Yan, Yi Duan, Zining Chen"
date: "`r Sys.Date()`"
site: bookdown::bookdown_site
---

# Introduction
The greenhouse effect is one of the important issues facing mankind in the 21st century. As the main gas causing the greenhouse effect, CO2 emissions have always been highly concerned. Since the industrial revolution, with the massive consumption of fossil fuels, CO2 emissions have increased year by year. As a global issue, does CO2 distribution have the same trend all over the world? Through monitoring stations around the world, we hope to discover the laws and trends of CO2 emissions and their distribution. Are there significant differences in CO2 concentration in different locations? In addition, The COVID-19 pandemic being the most consequential global event in the year of 2020 has impacted everyone and every country in the world. When all kinds of production and lifestyle are greatly affected, will CO2 emissions be affected accordingly? Therefore, we decide to conduct an analytical study on CO2 data collected by several observatory stations. We aim to use exploratory data analysis to study if there is any trends on CO2 emissions changes, whether there exists any regional effects on CO2 distribution and the effect of COVID-19 on CO2-emissions.
In the project, we collected the observatory data from The Scripps CO2 program to generate visualizations and conduct investigations on the CO2 emissions changing trend. We would like to carry out analysis from both geographic and time series perspectives and answer the following questions::

1) Through the CO2 data collected from a range of years, we can use time series to analysis its changing trend. Noting there are a number of observatory stations, there may exists some differences between their trends. 

2) Since the data is collected from several stations in different locations, their CO2 data may seem not the same. We want to exam the difference between them and analysis the factor causing the difference, for instance, their latitude and longitude.

3) During the COVID-19 period, what is the change of CO2 emissions trend? Does COVID-19 have a big impact on CO2 emissions?

In the following chapters, we will discuss these questions and provide some new insights on forecasting the future CO2 emissions.

Click [here](https://github.com/yhlpkucu/CO2DataAnalysis) for more details about this project. Check out each `.Rmd` file for the code for each chapter.